#!/usr/bin/env node
/**
 * sync-inbox.mjs — regenerate docs/INBOX.md from open comments.
 *
 * Usage:  node scripts/sync-inbox.mjs
 *
 * Reads unresolved comments and writes them to docs/INBOX.md, grouped by kind,
 * newest first, with change_request items at the top.
 *
 * TODO: point this at the real data source (Supabase Postgres) once the admin board
 *       writes comments. Swap readComments() for a DB query — everything below it
 *       works off the same shape and will not need to change.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(ROOT, "docs/_comments.json");
const OUTPUT = resolve(ROOT, "docs/INBOX.md");

const KINDS = ["change_request", "question", "note"]; // display order — CRs first
const KIND_LABEL = {
  change_request: "Change requests",
  question: "Questions",
  note: "Notes",
};
const KIND_BLURB = {
  change_request: "Something must change. Act on these first.",
  question: "Needs an answer. May or may not lead to a change.",
  note: "Context for later. No action required.",
};
const VALID_STATUS = ["open", "in_review", "resolved"];

/** Read comments from the stub file. Replace with a DB query when one exists. */
function readComments() {
  if (!existsSync(SOURCE)) {
    console.error(`✗ No comment source found at docs/_comments.json`);
    console.error(`  Create it, or point readComments() at the database.`);
    process.exit(1);
  }
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(SOURCE, "utf8"));
  } catch (err) {
    console.error(`✗ docs/_comments.json is not valid JSON: ${err.message}`);
    process.exit(1);
  }
  if (!Array.isArray(parsed.comments)) {
    console.error(`✗ docs/_comments.json must contain a "comments" array.`);
    process.exit(1);
  }
  return parsed.comments;
}

/** Warn loudly about malformed entries rather than silently dropping them. */
function validate(comments) {
  const problems = [];
  for (const c of comments) {
    if (!c.id) problems.push(`a comment is missing an id`);
    if (!KINDS.includes(c.kind)) problems.push(`${c.id}: unknown kind "${c.kind}"`);
    if (!VALID_STATUS.includes(c.status)) problems.push(`${c.id}: unknown status "${c.status}"`);
    if (c.status === "resolved" && (!c.resolution || !c.resolutionLink)) {
      problems.push(`${c.id}: resolved but missing a resolution note or link`);
    }
  }
  return problems;
}

function formatDate(iso) {
  if (!iso) return "unknown date";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? "invalid date" : d.toISOString().slice(0, 10);
}

function render(open) {
  const today = new Date().toISOString().slice(0, 10);
  const total = open.length;

  const lines = [
    "---",
    "id: DOC-012",
    "type: inbox",
    "status: active",
    "phase: null",
    "owner: james",
    "tags: [foundations]",
    "links: [DOC-001]",
    `updated: ${today}`,
    "---",
    "",
    "# Comment inbox",
    "",
    "<!-- GENERATED by scripts/sync-inbox.mjs — do not edit by hand.",
    "     Edit docs/_comments.json (or the database) and re-run the script. -->",
    "",
    `**${total} unresolved** · regenerated ${today}`,
    "",
    "Read this at the start of every session. Act on change requests, answer questions,",
    "then write a resolution (note + link) so the item clears on the next sync.",
    "",
  ];

  if (total === 0) {
    lines.push("Inbox is clear. Nothing needs attention.", "");
    return lines.join("\n");
  }

  for (const kind of KINDS) {
    const group = open
      .filter((c) => c.kind === kind)
      .sort((a, b) => new Date(b.created) - new Date(a.created)); // newest first

    if (group.length === 0) continue;

    lines.push(`## ${KIND_LABEL[kind]} (${group.length})`, "", `_${KIND_BLURB[kind]}_`, "");

    for (const c of group) {
      const flag = c.status === "in_review" ? " · _in review_" : "";
      lines.push(`### ${c.id} — on \`${c.doc}\`${flag}`, "");
      lines.push(`**${c.author}** · ${formatDate(c.created)}`, "");
      lines.push(c.body, "");
    }
  }

  return lines.join("\n");
}

// --- main --------------------------------------------------------------------
const comments = readComments();

const problems = validate(comments);
if (problems.length) {
  console.warn(`⚠ ${problems.length} problem(s) in the comment data:`);
  for (const p of problems) console.warn(`   ${p}`);
}

const open = comments.filter((c) => c.status !== "resolved");
const resolved = comments.length - open.length;

writeFileSync(OUTPUT, render(open), "utf8");

const byKind = KINDS.map((k) => `${open.filter((c) => c.kind === k).length} ${k}`).join(", ");
console.log(`✓ docs/INBOX.md — ${open.length} unresolved (${byKind}); ${resolved} resolved, hidden`);
